export const ADD_FLAT_TO_CART = "ADD_FLAT_TO_CART";
export const ADD_FLATMATE_TO_CART = "ADD_FLATMATE_TO_CART";
export const REMOVE_FLAT_CART_ITEM = "REMOVE_FLAT_CART_ITEM";
export const REMOVE_FLATMATE_CART_ITEM = "REMOVE_FLATMATE_CART_ITEM";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const UPDATE_FLAT_CART_TOTAL = "UPDATE_FLAT_CART_TOTAL";