export const ALL_FLATMATE_REQUEST = "ALL_FLATMATE_REQUEST";
export const ALL_FLATMATE_SUCCESS = "ALL_FLATMATE_SUCCESS";
export const ALL_FLATMATE_FAILED = "ALL_FLATMATE_FAILED";

export const FLATMATE_DETAILS_REQUEST = "FLATMATE_DETAILS_REQUEST";
export const FLATMATE_DETAILS_SUCCESS = "FLATMATE-DETAILS_SUCCESS";
export const FLATMATE_DETAILS_FAILED = "FLATMATE_DETAILS_FAILED";

export const CLEAR_ERRORS = "CLEAR_ERRORS";