export const ALL_FLATMATE_REQUEST = "ALL_FLATMATE_REQUEST";
export const ALL_FLATMATE_SUCCESS = "ALL_FLATMATE_SUCCESS";
export const ALL_FLATMATE_FAILED = "ALL_FLATMATE_FAILED";

export const CLEAR_ERRORS = "CLEAR_ERRORS";