export const ALL_FLAT_REQUEST = "ALL_FLAT_REQUEST";
export const ALL_FLAT_SUCCESS = "ALL_FLAT_SUCCESS";
export const ALL_FLAT_FAILED = "ALL_FLAT_FAILED";

export const FLAT_DETAILS_REQUEST = "FLAT_DETAILS_REQUEST";
export const FLAT_DETAILS_SUCCESS = "FLAT-DETAILS_SUCCESS";
export const FLAT_DETAILS_FAILED = "FLAT_DETAILS_FAILED";

export const CLEAR_ERRORS = "CLEAR_ERRORS";